---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(tidyverse)
library(plotly)
library(flexdashboard)

```

```{r}

nyc_inspec = read_csv("./data/nyc_inspec.csv") %>%
              filter(score >= 0) %>%
              filter(latitude != 0) %>%
              filter(longitude != 0) %>%
              distinct(dba, latitude, longitude, .keep_all=TRUE)

cuisines = nyc_inspec

# Shorten long names
for (row in 1:nrow(cuisines)) {
  if (cuisines[row, 'cuisine_description'] == "Ice Cream, Gelato, Yogurt, Ices") {
    cuisines[row, 'cuisine_description'] = "Ice Cream"
  }
  if (cuisines[row, 'cuisine_description'] == "Sandwiches/Salads/Mixed Buffet") {
    cuisines[row, 'cuisine_description'] = "Sandwiches/Salads"
  }
  if (cuisines[row, 'cuisine_description'] == "Café/Coffee/Tea") {
    cuisines[row, 'cuisine_description'] = "Coffee/Tea"
  }
  if (cuisines[row, 'cuisine_description'] == "Juice, Smoothies, Fruit Salads") {
    cuisines[row, 'cuisine_description'] = "Juice/Smoothies"
  }
  if (cuisines[row, 'cuisine_description'] == "Latin (Cuban, Dominican, Puerto Rican, South & Central American)") {
    cuisines[row, 'cuisine_description'] = "Latin"
  }
}

common_cuisines = cuisines %>% count(cuisine_description, sort=TRUE) %>%
  top_n(14) %>% select(cuisine_description)
              
```

Column {data-width=650}
-----------------------------------------------------------------------

### Map of scores (lower scores are better)

```{r}

nyc_inspec %>%
  mutate(text_label = str_c(dba, "\nCuisine: ", cuisine_description,
                            "\nScore: ", score)) %>%
  select(dba,
         cuisine_description,
         latitude,
         longitude,
         score,
         text_label) %>%
  plot_ly(x = ~longitude,
          y = ~latitude,
          type = "scatter",
          mode = "markers",
          color = ~score,
          text = ~text_label)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Scores by borough

```{r}

nyc_inspec %>% 
  select(boro, score) %>%
  plot_ly(y = ~score, color = ~boro, type = "box")

```

### Most common cuisine types

```{r}

inner_join(cuisines, common_cuisines, by = "cuisine_description") %>%
                count(cuisine_description) %>%
                mutate(cuisine = fct_reorder(cuisine_description, -n)) %>%
                select(cuisine, n) %>%
                plot_ly(x = ~cuisine, y = ~n, color = ~cuisine, type = "bar")

```